platform :ios, '14.0'

use_frameworks!

## Without use_frameworks!
target 'Segment-Firebase_Example' do
  # Use default subspec
  pod 'Segment-Firebase', :path => '../'
  
  target 'Segment-Firebase_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end
